---
kind: pipeline
type: docker
name: build

steps:
  - name: lint
    image: code.pztrn.name/containers/mirror/golangci/golangci-lint:v1.46.2
    environment:
      CGO_ENABLED: 0
    commands:
      - golangci-lint run

  - name: test
    image: code.pztrn.name/containers/mirror/golang:1.18.3-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - go test ./...

  - name: docker
    image: code.pztrn.name/containers/mirror/plugins/docker:20.13.0
    when:
      branch: ["master"]
    settings:
      registry: code.pztrn.name
      username: drone
      password:
        from_secret: drone_secret
      repo: code.pztrn.name/apps/opensaps
      auto_tag: true
    depends_on:
      - lint
      - test
