run:
  deadline: 5m
linters:
  enable-all: true
  disable:
    # Because globals might exist, but according to our codestyle they
    # should be lowercased and considered as unexported.
    - gochecknoglobals
    # This linter goes crazy for nothing (almost).
    - funlen
    # Deprecated things.
    - exhaustivestruct
linters-settings:
  lll:
    line-length: 128
  cyclop:
    max-complexity: 40

issues:
  exclude-rules:
    # There will be some ToDos.
    - linters:
        - godox
      text: "TODO"
